#!/usr/bin/env bash
# Copyright (c) 2019 University of Exeter
#               2018-2019 University of Paris-Saclay
#               2018-2019 The University of Sheffield
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in
#    the documentation and/or other materials provided with the
#    distribution.
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
# FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
# COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
# INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
# BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
# ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.
#
# SPDX-License-Identifier: BSD-2-Clause

set -e
if [ ! -f $ISABELLE_HOME_USER/DOF/document-template/build_lib.sh ]; then
    >&2 echo ""
    >&2 echo "Error: Isabelle/DOF not installed"
    >&2 echo "====="
    >&2 echo "This is a Isabelle/DOF project. The document preparation requires"
    >&2 echo "the Isabelle/DOF framework. Please obtain the framework by cloning"
    >&2 echo "the Isabelle/DOF git repository, i.e.: "
    >&2 echo "    git clone https://git.logicalhacking.com/Isabelle_DOF/Isabelle_DOF"
    >&2 echo "You can install the framework as follows:"
    >&2 echo "    cd Isabelle_DOF/document-generator"
    >&2 echo "    ./install"
    >&2 echo ""
    exit 1
fi

cp $ISABELLE_HOME_USER/DOF/document-template/build_lib.sh .
source build_lib.sh
